GeneralConfig:
  app_scenes: "jindie" # what scenes this model used
  alphabet: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
             'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
             'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L',
             'Z', 'X', 'C', 'V', 'B', 'N', 'M',
             'q','w','e','r','t','y','u','i','o','p',
             'a','s','d','f','g','h','j','k','l',
             'z','x','c','v','b','n','m','-']
  short_size: 32 #'short_size has to be a multiple of 16'
  length: 4 # length of verification; TODO support variable length of verification
TrainConfig:
  train_data_path: "/home/shizai/adolf/data/jindie/" # where data storage
  Device: "cpu" # use cpu or gpu;"cpu" or "cuda"
  model_path: "Identify_English/weight" # path to save model
  epochs: 1200 # if you don't know what meaning,using default
  lr: 1e-3 # if you don't know what meaning,using default
  batch_size: 256 # if you don't know what meaning,using default
  num_works: 0 # how many processes are used to data preprocess
InferenceConfig:
  Device: "cpu" # use cpu or gpu;"cpu" or "cuda"
  model_path: "" # where predict model storage
